Arcitecture mvc
SimonSolv/industrial_development pull request #13
Opened 2022-04-02 17:02 UTC by SimonSolv

Сделал все по ДЗ, но не все получилось гладко. А именно: 
в ProfileTableViewCell закоментированна строка 37 "ProfileViewController.jpenGallery()", так как компиллятор на нее ругается. Это была попытка спрятать действие соответствующей кнопки на уровень ниже, однако при этом возникают трудности с тем, чтобы "достучаться" до исходного ViewController, буду рад за подсказку как это правильно делать ибо данная ошибка сопровождает меня очень часто.
По той же причине закомментирована 129 строка в PhotosTableViewCell.
Спасибо за проверку и ценные замечания!

2022-04-27 09:04 UTC, Konskii requested changes
Очень много замечаний и в корне не верных решений, нарушаются правила ООП и SOLID. 
По поводу Вашего вопроса - ответ в комментарии про SOLID и ООП - вы изначально неправильно строите логику общения элементов приложения.
Отправлю на доработку, жду изменений)

Если есть вопросы, велкам в телеграмм: @t_skr

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedModel.swift
> +    func check() -> Bool {
По заданию модель должна иметь метод, в котором проверяет переданный ей `word`. Сейчас такого метода нет, а `word` передается с помощью инициализатора. 
Поправить

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedModel.swift
> +    var controlWord = "Password"
`private` и `let`

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedModel.swift
> +            return true
вместо возвращаемого значения у метода по заданию нужно передавать нотификацию, т.е использовать Notification Center.
Поправить

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedViewController.swift
> +    let firstTextfield: UITextField = {
ui элементы выгоднее реализовывать с помощью `lazy var`.
Так же не забывайте про модификаторы доступа)

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedViewController.swift
> +        let btn = CustomButton(title: "Check", titleColor: .white) {
почему в вычисляемой переменной присутствует бизнес-логика? Такого быть не должно. Все проверки итд вынести в отдельные методы. Кнопка должна только отображаться и сообщать о том, что пользователь нажал на нее

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedViewController.swift
> + //       btn.setTitle("New Post 2", for: .normal)
следует убрать закомментированный код

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedViewController.swift
> +            self.tapNewPostButton()
подумайте как передать кнопке просто функцию, чтобы было что-то вроде:
`let btn = CustomButton(title: "New Post 2", titleColor: .white, onTap: tapNewPostButton)`

2022-04-27 09:04 UTC, Konskii commented on Navigation/Feed/FeedViewController.swift
> +
пустая строка
чтобы избежать таких явных ошибок и писать более чистый код - погуглите на тему SwiftLint

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/CustomButton.swift
> +//final class UIButton2: UIButton {
почему столько закомментированного кода?

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/GalleryCollectionViewCell.swift
> +            ProfileViewController().openGallery()
Ячейка не должна ничего знать про viewController, Вспомните принципы SOLID и ООП.
Вы должны передать ячейке функцию viewController, а не она должна сама вызвать ее.
Еще лучшим решением будет использование паттерны делегата. 
Переделать

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/GalleryViewController.swift
> +//        view.translatesAutoresizingMaskIntoConstraints = false
почему закомментировали?

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/LoginViewController.swift
> +
ненужные отступы после mainView, не проставлены модификаторы доступа у всех свойств

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/LoginViewController.swift
> +            if self.delegate?.checkPswd(login: self.userName ?? "0", password: self.userPassword ?? "0") == true {
убрать всю бизнес-логику

2022-04-27 09:04 UTC, Konskii commented on Navigation/Profile/LoginViewController.swift
>          var textfield: UITextField = UITextField(frame: CGRect(x: 0, y: 0, width: 0, height: 50))
Очень много кода для кастомизации UI классов.
Я бы посоветовал вынести всю Кастомизацию в extension для UI класса и создать "типы" того как должна выглядеть кнопка, текстфилд итд. По итогу вам потребуется просто вызвать метод и передать тип который вы хотели бы видеть, что-то вроде:
`textField.setStyle(style: .light)`
style принимает значения из созданного enum стилей

2022-05-15 18:58 UTC, SimonSolv commented
@Konskii Спасибо за ваши замечания! Прошелся по всем, все поправил.
Единственное - полетели все #selector у текстфилдов. Еще до того, как я им передал функцию setStyle().
Ошибка крашит все приложение: Thread 1: "+[Navigation.LoginViewController passwordFieldTapped:]: unrecognized selector sent to class 0x1044eada0"
Не разобрался в чем причина, так как функционал не менял и это у меня впервые.

2022-05-27 19:05 UTC, merged